spring:
  application:
    name: learn-mybatis
  datasource:
    url: jdbc:mysql://192.168.1.117:3306/my_learn?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.learn.entity
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰功能
